### PR TITLE
Improve IMAP response handling

### PR DESCRIPTION
**Pull request by szymekjanaczek**
According to #270 

I know, we still have to update legacy protocol. It's just a draft.

### CODE REVIEW

**Comment by szymekjanaczek** [comment]
Okay, removed `ext-imap` usage.

**Comment by szymekjanaczek** [comment]
Hi, what do you think about merging it? 👉👈

**Comment by Webklex** [comment]
Hi @szymekjanaczek ,
this line makes me nervous:
```php
protected function assumedNextLine(string $start): bool {
    return str_starts_with($this->nextLine(), $start);
}
```
This would lock the code to require php > 8.  I'm having an inner discussion how I should proceed. I was sure to have talked about it somewhere (but can't find it anymore). Frankly I'm nervous to exclude a whole bunch of people but I'm also aware of the fact that you can't support everything and supporting a wide range causes a whole bunch of new issues.

I haven't forgotten this pull request. In fact I thought about it a lot, I just don't know how to proceed.

Best regards,

**Comment by szymekjanaczek** [comment]
Hi @Webklex!
You're right, this must stay at the lower version of PHP - my mistake.
According to the rest of your message, you probably are talking about #270, aren't you?

**Comment by Webklex** [comment]
Hey @szymekjanaczek ,
I wouldn't call it a mistake. It's a valid point to use modern functions :+1: 

I've scraped the topic it a little bit in 270 but that's not what I've meant.

Anyway whats your thought on it? I can see arguments for both. How would you decide?

Best regards and thanks for your help & support,

**Comment by szymekjanaczek** [comment]
Hello again, @Webklex 

In my honest opinion we should move forward and create a new branch using PHPv8.1 with tools: sniffers, static analysis, unit tests, refactoring helpers, ci/cd on github to speed-up cooperation with new collaborators, and so on - to open the way for the further updates. And ofc some performance improvements - like using bulk IMAP operations.
I know that would be a breaking change, but necessary to keep this library useable in new projects - know it from my own experience. We're using this lib in out project too.

That's my idea, now we need devs and quite advanced knowledge about IMAP usage.

**Comment by szymekjanaczek** [comment]
Hi again @Webklex!

What do you think about merging it? Switch from mixed response to bool was a breaking change for some of my features ;(

Thanks in advance, greetings!

**Comment by szymekjanaczek** [comment]
Nice to hear that - feel free to ping me when need anything!

Have a nice evening!

**Comment by Webklex** [comment]
Hi @szymekjanaczek ,
I just pushed my last weeks work. We now have an actual `Response::class` to work with and real unit tests. 

Btw happy new year :)

Best regards,

**Pull request merged**
