### PR TITLE
Support maintained PHP Versions & introduce Rector 

### PR DESCRIPTION
**Pull request by boekkooi-lengoo**
Hello,
First of thank you very much for maintaining this library! It saved me a ton of time and effort!

This PR is in bumping the support PHP version for this library to PHP 7.4 to match the currently support [PHP versions](https://www.php.net/supported-versions.php) (commit https://github.com/Webklex/php-imap/commit/733be54f23d07591b6679e66127a13dd38fe0c4f and https://github.com/Webklex/php-imap/commit/ae0ceb4fd289abe1f48bff524a4cc5768e14b84d).

After the PHP version update I introduced [rector ](https://github.com/rectorphp/rector) to help update and tweak the code based.
This also involved some manual changes and I have already fix some wrong types and other things.

I understand that this PR maybe way to big but I at least wanted to share my work even if its just for inspiration.
Thanks again for your work on this library!

Cheers,
Warnar

### CODE REVIEW

**Comment by Webklex** [comment]
Hi @boekkooi-lengoo ,
wow thanks a lot for your pull request!

I'll check it out and probably merge it this weekend :)

Best regards,

**Comment by Webklex** [comment]
Hi @boekkooi-lengoo ,
I'm currently not sure about the potential implication of requiring rector. I know to little about it to blindly merge it. Especially the potential overhead. Guess I have to do some more reading.

Best regards,

**Comment by boekkooi-lengoo** [comment]
Hey @Webklex,

I totally understand and I would myself also not require Rector I just used the tool to help improve the code base automatically instead of manually. This is also the reason why I did not add a rector dry-run to the GitHub Actions workflow.

Thanks for taking the time looking at the PR :smile:

**Comment by Webklex** [comment]
Hi @boekkooi-lengoo ,
unfortunately I wasn't able to merge your pull request. However I would like to acknowledge you work and your suggestions which indeed influenced my changes. Please feel free to simply push a " " or "." - I'll happily merge it so you'll get listed as a contributor.

Best regards and a happy new year,

**Comment by boekkooi-lengoo** [comment]
Hey @Webklex,

Thanks again for looking at the PR and I'm very happy to hear that it helped you and the project.
I will give the latest version of the library a test in the coming weeks and will happy contribute if I find something to improve.

Thanks again for supporting this library and I wish you all the best this new year.

**Pull request closed without merging**
